Rails.application.routes.draw do
  get 'services', to: 'services#index'
  get 'services/index'
  get 'services/helpdesk'  
  get 'services/promos'
  get 'services/fundraisers'
  get 'services/smartcontracts'
  get 'services/dapps'
  get 'services/configuration'
  get 'services/nodes'
  get 'tech/summary'
  get 'tech/specs'
  get 'tech/topo'
  get 'tech/primer'
  get 'tech/witness'
  get 'tech/solidity'
  get 'tech/config_file'
  get 'tech/cluster'
  get 'tech/summary'
  get 'tech/specs'
  get 'tech/topo'
  get 'tech/primer'
  get 'tech/witness'
  get 'tech/solidity'
  get 'tech/config'
  get 'tech/cluster'
  get 'questions/faq'
  get 'questions/points'
  get 'questions/voting'
  get 'questions/wallets'
  get 'questions/security'
  get 'rewards/index'
  get 'support/index'
  get 'support/dapps'
  get 'support/contests'
  get 'support/staging'
  get 'keystore', to: 'support#keystore'
  get 'support/keystore'
  get 'starter', to: 'support#starter'
  get 'support/starter'
  get 'support/fledglings'
  get 'support/github'
  get 'support/contact'
  get 'home', to: 'support#index'

  root to: 'support#index' 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
